config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_mycustomtheme.omp.json:
    src: mycustomtheme.omp.json
    dst: ~/.mycustomtheme.omp.json
    chmod: '755'
  f_zprofile:
    src: zprofile
    dst: ~/.zprofile
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
profiles:
  Jorans-MacBook-Pro.local:
    dotfiles:
    - f_mycustomtheme.omp.json
    - f_zprofile
    - f_zshenv
    - f_zshrc
    - f_bashrc
    - f_gitconfig
