config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
profiles:
  Jorans-MacBook-Pro.local:
    dotfiles:
    - f_bashrc
    - f_gitconfig
    - f_p10k.zsh
    - f_zshrc
    - f_zshenv
