config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_zprofile:
    src: zprofile
    dst: ~/.zprofile
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_testcontainers.properties:
    src: testcontainers.properties
    dst: ~/.testcontainers.properties
  f_mycustomtheme.omp.json:
    src: mycustomtheme.omp.json
    dst: ~/.mycustomtheme.omp.json
    chmod: '755'
  f_ideavimrc:
    src: ideavimrc
    dst: ~/.ideavimrc
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_:x:
    src: config/nvim/:x
    dst: ~/.config/nvim/:x
  f_init.lua:
    src: config/nvim/init.lua
    dst: ~/.config/nvim/init.lua
  f_lazy-lock.json:
    src: config/nvim/lazy-lock.json
    dst: ~/.config/nvim/lazy-lock.json
  d_lua:
    src: config/nvim/lua
    dst: ~/.config/nvim/lua
profiles:
  Jorans-MacBook-Pro.local:
    dotfiles:
    - f_zprofile
    - f_zshenv
    - f_zshrc
    - f_bashrc
    - f_gitconfig
    - f_testcontainers.properties
    - f_mycustomtheme.omp.json
    - f_ideavimrc
    - d_nvim
    - f_:x
    - f_init.lua
    - f_lazy-lock.json
    - d_lua
